// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snn_infer_snn_infer_Pipeline_VITIS_LOOP_244_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        empty_16,
        empty_17,
        empty,
        hidden1_address0,
        hidden1_ce0,
        hidden1_we0,
        hidden1_d0,
        grp_fu_827_p_din0,
        grp_fu_827_p_din1,
        grp_fu_827_p_opcode,
        grp_fu_827_p_dout0,
        grp_fu_827_p_ce,
        grp_fu_306_p_din0,
        grp_fu_306_p_din1,
        grp_fu_306_p_opcode,
        grp_fu_306_p_dout0,
        grp_fu_306_p_ce,
        grp_fu_831_p_din0,
        grp_fu_831_p_din1,
        grp_fu_831_p_opcode,
        grp_fu_831_p_dout0,
        grp_fu_831_p_ce,
        grp_fu_313_p_din0,
        grp_fu_313_p_din1,
        grp_fu_313_p_dout0,
        grp_fu_313_p_ce,
        grp_fu_835_p_din0,
        grp_fu_835_p_din1,
        grp_fu_835_p_dout0,
        grp_fu_835_p_ce,
        grp_fu_839_p_din0,
        grp_fu_839_p_din1,
        grp_fu_839_p_dout0,
        grp_fu_839_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] empty_16;
input  [31:0] empty_17;
input  [31:0] empty;
output  [5:0] hidden1_address0;
output   hidden1_ce0;
output   hidden1_we0;
output  [31:0] hidden1_d0;
output  [31:0] grp_fu_827_p_din0;
output  [31:0] grp_fu_827_p_din1;
output  [1:0] grp_fu_827_p_opcode;
input  [31:0] grp_fu_827_p_dout0;
output   grp_fu_827_p_ce;
output  [31:0] grp_fu_306_p_din0;
output  [31:0] grp_fu_306_p_din1;
output  [0:0] grp_fu_306_p_opcode;
input  [31:0] grp_fu_306_p_dout0;
output   grp_fu_306_p_ce;
output  [31:0] grp_fu_831_p_din0;
output  [31:0] grp_fu_831_p_din1;
output  [1:0] grp_fu_831_p_opcode;
input  [31:0] grp_fu_831_p_dout0;
output   grp_fu_831_p_ce;
output  [31:0] grp_fu_313_p_din0;
output  [31:0] grp_fu_313_p_din1;
input  [31:0] grp_fu_313_p_dout0;
output   grp_fu_313_p_ce;
output  [31:0] grp_fu_835_p_din0;
output  [31:0] grp_fu_835_p_din1;
input  [31:0] grp_fu_835_p_dout0;
output   grp_fu_835_p_ce;
output  [31:0] grp_fu_839_p_din0;
output  [31:0] grp_fu_839_p_din1;
input  [31:0] grp_fu_839_p_dout0;
output   grp_fu_839_p_ce;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln244_fu_156_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [7:0] fc1_weights_address0;
wire   [31:0] fc1_weights_q0;
wire   [7:0] fc1_weights_address1;
wire   [31:0] fc1_weights_q1;
wire   [7:0] fc1_weights_address2;
wire   [31:0] fc1_weights_q2;
wire    ap_block_pp0_stage0_11001;
reg   [6:0] i_4_reg_246;
reg   [6:0] i_4_reg_246_pp0_iter1_reg;
reg   [6:0] i_4_reg_246_pp0_iter2_reg;
reg   [6:0] i_4_reg_246_pp0_iter3_reg;
reg   [6:0] i_4_reg_246_pp0_iter4_reg;
reg   [6:0] i_4_reg_246_pp0_iter5_reg;
reg   [6:0] i_4_reg_246_pp0_iter6_reg;
reg   [6:0] i_4_reg_246_pp0_iter7_reg;
reg   [6:0] i_4_reg_246_pp0_iter8_reg;
reg   [6:0] i_4_reg_246_pp0_iter9_reg;
reg   [6:0] i_4_reg_246_pp0_iter10_reg;
reg   [6:0] i_4_reg_246_pp0_iter11_reg;
reg   [6:0] i_4_reg_246_pp0_iter12_reg;
reg   [6:0] i_4_reg_246_pp0_iter13_reg;
reg   [6:0] i_4_reg_246_pp0_iter14_reg;
reg   [6:0] i_4_reg_246_pp0_iter15_reg;
reg   [6:0] i_4_reg_246_pp0_iter16_reg;
reg   [6:0] i_4_reg_246_pp0_iter17_reg;
reg   [6:0] i_4_reg_246_pp0_iter18_reg;
reg   [6:0] i_4_reg_246_pp0_iter19_reg;
wire   [7:0] sub_ln247_fu_184_p2;
reg   [7:0] sub_ln247_reg_255;
reg   [7:0] sub_ln247_reg_255_pp0_iter1_reg;
reg   [7:0] sub_ln247_reg_255_pp0_iter2_reg;
reg   [7:0] sub_ln247_reg_255_pp0_iter3_reg;
reg   [7:0] sub_ln247_reg_255_pp0_iter4_reg;
reg   [7:0] sub_ln247_reg_255_pp0_iter5_reg;
reg   [7:0] sub_ln247_reg_255_pp0_iter6_reg;
reg   [7:0] sub_ln247_reg_255_pp0_iter7_reg;
reg   [7:0] sub_ln247_reg_255_pp0_iter8_reg;
reg   [7:0] sub_ln247_reg_255_pp0_iter9_reg;
reg   [31:0] mul7_i_reg_271;
reg   [31:0] sum_reg_286;
reg   [31:0] mul7_1_i_reg_291;
reg   [31:0] sum_2_reg_306;
reg   [31:0] mul7_2_i_reg_311;
reg   [31:0] sum_3_reg_316;
wire   [63:0] zext_ln247_fu_190_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln247_1_fu_205_p1;
wire   [63:0] zext_ln247_2_fu_215_p1;
wire   [63:0] zext_ln244_fu_220_p1;
reg   [6:0] i_fu_48;
wire   [6:0] add_ln244_fu_162_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i_4;
reg    fc1_weights_ce2_local;
reg    fc1_weights_ce1_local;
reg    fc1_weights_ce0_local;
reg    hidden1_we0_local;
reg    hidden1_ce0_local;
wire   [5:0] trunc_ln247_fu_172_p1;
wire   [7:0] p_shl_fu_176_p3;
wire   [7:0] zext_ln244_1_fu_168_p1;
wire   [7:0] add_ln247_fu_200_p2;
wire   [7:0] add_ln247_1_fu_210_p2;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 i_fu_48 = 7'd0;
#0 ap_done_reg = 1'b0;
end

snn_infer_snn_infer_Pipeline_VITIS_LOOP_244_1_fc1_weights_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 192 ),
    .AddressWidth( 8 ))
fc1_weights_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fc1_weights_address0),
    .ce0(fc1_weights_ce0_local),
    .q0(fc1_weights_q0),
    .address1(fc1_weights_address1),
    .ce1(fc1_weights_ce1_local),
    .q1(fc1_weights_q1),
    .address2(fc1_weights_address2),
    .ce2(fc1_weights_ce2_local),
    .q2(fc1_weights_q2)
);

snn_infer_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter19_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln244_fu_156_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_48 <= add_ln244_fu_162_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_48 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        i_4_reg_246_pp0_iter10_reg <= i_4_reg_246_pp0_iter9_reg;
        i_4_reg_246_pp0_iter11_reg <= i_4_reg_246_pp0_iter10_reg;
        i_4_reg_246_pp0_iter12_reg <= i_4_reg_246_pp0_iter11_reg;
        i_4_reg_246_pp0_iter13_reg <= i_4_reg_246_pp0_iter12_reg;
        i_4_reg_246_pp0_iter14_reg <= i_4_reg_246_pp0_iter13_reg;
        i_4_reg_246_pp0_iter15_reg <= i_4_reg_246_pp0_iter14_reg;
        i_4_reg_246_pp0_iter16_reg <= i_4_reg_246_pp0_iter15_reg;
        i_4_reg_246_pp0_iter17_reg <= i_4_reg_246_pp0_iter16_reg;
        i_4_reg_246_pp0_iter18_reg <= i_4_reg_246_pp0_iter17_reg;
        i_4_reg_246_pp0_iter19_reg <= i_4_reg_246_pp0_iter18_reg;
        i_4_reg_246_pp0_iter2_reg <= i_4_reg_246_pp0_iter1_reg;
        i_4_reg_246_pp0_iter3_reg <= i_4_reg_246_pp0_iter2_reg;
        i_4_reg_246_pp0_iter4_reg <= i_4_reg_246_pp0_iter3_reg;
        i_4_reg_246_pp0_iter5_reg <= i_4_reg_246_pp0_iter4_reg;
        i_4_reg_246_pp0_iter6_reg <= i_4_reg_246_pp0_iter5_reg;
        i_4_reg_246_pp0_iter7_reg <= i_4_reg_246_pp0_iter6_reg;
        i_4_reg_246_pp0_iter8_reg <= i_4_reg_246_pp0_iter7_reg;
        i_4_reg_246_pp0_iter9_reg <= i_4_reg_246_pp0_iter8_reg;
        mul7_1_i_reg_291 <= grp_fu_835_p_dout0;
        mul7_2_i_reg_311 <= grp_fu_839_p_dout0;
        mul7_i_reg_271 <= grp_fu_313_p_dout0;
        sub_ln247_reg_255_pp0_iter2_reg <= sub_ln247_reg_255_pp0_iter1_reg;
        sub_ln247_reg_255_pp0_iter3_reg <= sub_ln247_reg_255_pp0_iter2_reg;
        sub_ln247_reg_255_pp0_iter4_reg <= sub_ln247_reg_255_pp0_iter3_reg;
        sub_ln247_reg_255_pp0_iter5_reg <= sub_ln247_reg_255_pp0_iter4_reg;
        sub_ln247_reg_255_pp0_iter6_reg <= sub_ln247_reg_255_pp0_iter5_reg;
        sub_ln247_reg_255_pp0_iter7_reg <= sub_ln247_reg_255_pp0_iter6_reg;
        sub_ln247_reg_255_pp0_iter8_reg <= sub_ln247_reg_255_pp0_iter7_reg;
        sub_ln247_reg_255_pp0_iter9_reg <= sub_ln247_reg_255_pp0_iter8_reg;
        sum_2_reg_306 <= grp_fu_306_p_dout0;
        sum_3_reg_316 <= grp_fu_831_p_dout0;
        sum_reg_286 <= grp_fu_827_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        i_4_reg_246 <= ap_sig_allocacmp_i_4;
        i_4_reg_246_pp0_iter1_reg <= i_4_reg_246;
        sub_ln247_reg_255 <= sub_ln247_fu_184_p2;
        sub_ln247_reg_255_pp0_iter1_reg <= sub_ln247_reg_255;
    end
end

always @ (*) begin
    if (((icmp_ln244_fu_156_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter19_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_4 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_4 = i_fu_48;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        fc1_weights_ce0_local = 1'b1;
    end else begin
        fc1_weights_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        fc1_weights_ce1_local = 1'b1;
    end else begin
        fc1_weights_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fc1_weights_ce2_local = 1'b1;
    end else begin
        fc1_weights_ce2_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter20 == 1'b1))) begin
        hidden1_ce0_local = 1'b1;
    end else begin
        hidden1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter20 == 1'b1))) begin
        hidden1_we0_local = 1'b1;
    end else begin
        hidden1_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln244_fu_162_p2 = (ap_sig_allocacmp_i_4 + 7'd1);

assign add_ln247_1_fu_210_p2 = (sub_ln247_reg_255_pp0_iter9_reg + 8'd2);

assign add_ln247_fu_200_p2 = (sub_ln247_reg_255_pp0_iter4_reg + 8'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign fc1_weights_address0 = zext_ln247_2_fu_215_p1;

assign fc1_weights_address1 = zext_ln247_1_fu_205_p1;

assign fc1_weights_address2 = zext_ln247_fu_190_p1;

assign grp_fu_306_p_ce = 1'b1;

assign grp_fu_306_p_din0 = sum_reg_286;

assign grp_fu_306_p_din1 = mul7_1_i_reg_291;

assign grp_fu_306_p_opcode = 2'd0;

assign grp_fu_313_p_ce = 1'b1;

assign grp_fu_313_p_din0 = fc1_weights_q2;

assign grp_fu_313_p_din1 = empty_16;

assign grp_fu_827_p_ce = 1'b1;

assign grp_fu_827_p_din0 = mul7_i_reg_271;

assign grp_fu_827_p_din1 = 32'd0;

assign grp_fu_827_p_opcode = 2'd0;

assign grp_fu_831_p_ce = 1'b1;

assign grp_fu_831_p_din0 = sum_2_reg_306;

assign grp_fu_831_p_din1 = mul7_2_i_reg_311;

assign grp_fu_831_p_opcode = 2'd0;

assign grp_fu_835_p_ce = 1'b1;

assign grp_fu_835_p_din0 = fc1_weights_q1;

assign grp_fu_835_p_din1 = empty_17;

assign grp_fu_839_p_ce = 1'b1;

assign grp_fu_839_p_din0 = fc1_weights_q0;

assign grp_fu_839_p_din1 = empty;

assign hidden1_address0 = zext_ln244_fu_220_p1;

assign hidden1_ce0 = hidden1_ce0_local;

assign hidden1_d0 = sum_3_reg_316;

assign hidden1_we0 = hidden1_we0_local;

assign icmp_ln244_fu_156_p2 = ((ap_sig_allocacmp_i_4 == 7'd64) ? 1'b1 : 1'b0);

assign p_shl_fu_176_p3 = {{trunc_ln247_fu_172_p1}, {2'd0}};

assign sub_ln247_fu_184_p2 = (p_shl_fu_176_p3 - zext_ln244_1_fu_168_p1);

assign trunc_ln247_fu_172_p1 = ap_sig_allocacmp_i_4[5:0];

assign zext_ln244_1_fu_168_p1 = ap_sig_allocacmp_i_4;

assign zext_ln244_fu_220_p1 = i_4_reg_246_pp0_iter19_reg;

assign zext_ln247_1_fu_205_p1 = add_ln247_fu_200_p2;

assign zext_ln247_2_fu_215_p1 = add_ln247_1_fu_210_p2;

assign zext_ln247_fu_190_p1 = sub_ln247_fu_184_p2;

endmodule //snn_infer_snn_infer_Pipeline_VITIS_LOOP_244_1
