// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snn_infer_snn_infer_Pipeline_VITIS_LOOP_308_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        hidden2_address0,
        hidden2_ce0,
        hidden2_q0,
        lif2_neurons_v_membrane_address0,
        lif2_neurons_v_membrane_ce0,
        lif2_neurons_v_membrane_we0,
        lif2_neurons_v_membrane_d0,
        lif2_neurons_v_membrane_address1,
        lif2_neurons_v_membrane_ce1,
        lif2_neurons_v_membrane_q1,
        lif2_neurons_v_threshold_address0,
        lif2_neurons_v_threshold_ce0,
        lif2_neurons_v_threshold_q0,
        grp_fu_313_p_din0,
        grp_fu_313_p_din1,
        grp_fu_313_p_dout0,
        grp_fu_313_p_ce,
        grp_fu_327_p_din0,
        grp_fu_327_p_din1,
        grp_fu_327_p_opcode,
        grp_fu_327_p_dout0,
        grp_fu_327_p_ce,
        grp_fu_827_p_din0,
        grp_fu_827_p_din1,
        grp_fu_827_p_opcode,
        grp_fu_827_p_dout0,
        grp_fu_827_p_ce,
        grp_fu_306_p_din0,
        grp_fu_306_p_din1,
        grp_fu_306_p_opcode,
        grp_fu_306_p_dout0,
        grp_fu_306_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] hidden2_address0;
output   hidden2_ce0;
input  [31:0] hidden2_q0;
output  [4:0] lif2_neurons_v_membrane_address0;
output   lif2_neurons_v_membrane_ce0;
output   lif2_neurons_v_membrane_we0;
output  [31:0] lif2_neurons_v_membrane_d0;
output  [4:0] lif2_neurons_v_membrane_address1;
output   lif2_neurons_v_membrane_ce1;
input  [31:0] lif2_neurons_v_membrane_q1;
output  [4:0] lif2_neurons_v_threshold_address0;
output   lif2_neurons_v_threshold_ce0;
input  [31:0] lif2_neurons_v_threshold_q0;
output  [31:0] grp_fu_313_p_din0;
output  [31:0] grp_fu_313_p_din1;
input  [31:0] grp_fu_313_p_dout0;
output   grp_fu_313_p_ce;
output  [31:0] grp_fu_327_p_din0;
output  [31:0] grp_fu_327_p_din1;
output  [4:0] grp_fu_327_p_opcode;
input  [0:0] grp_fu_327_p_dout0;
output   grp_fu_327_p_ce;
output  [31:0] grp_fu_827_p_din0;
output  [31:0] grp_fu_827_p_din1;
output  [1:0] grp_fu_827_p_opcode;
input  [31:0] grp_fu_827_p_dout0;
output   grp_fu_827_p_ce;
output  [31:0] grp_fu_306_p_din0;
output  [31:0] grp_fu_306_p_din1;
output  [0:0] grp_fu_306_p_opcode;
input  [31:0] grp_fu_306_p_dout0;
output   grp_fu_306_p_ce;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln308_fu_121_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln308_fu_133_p1;
reg   [63:0] zext_ln308_reg_243;
reg   [63:0] zext_ln308_reg_243_pp0_iter1_reg;
reg   [63:0] zext_ln308_reg_243_pp0_iter2_reg;
reg   [63:0] zext_ln308_reg_243_pp0_iter3_reg;
reg   [63:0] zext_ln308_reg_243_pp0_iter4_reg;
reg   [63:0] zext_ln308_reg_243_pp0_iter5_reg;
reg   [63:0] zext_ln308_reg_243_pp0_iter6_reg;
reg   [63:0] zext_ln308_reg_243_pp0_iter7_reg;
reg   [63:0] zext_ln308_reg_243_pp0_iter8_reg;
reg   [63:0] zext_ln308_reg_243_pp0_iter9_reg;
reg   [63:0] zext_ln308_reg_243_pp0_iter10_reg;
reg   [31:0] hidden2_load_reg_254;
reg   [4:0] neuron_v_membrane_reg_259;
reg   [4:0] neuron_v_membrane_reg_259_pp0_iter3_reg;
reg   [4:0] neuron_v_membrane_reg_259_pp0_iter4_reg;
reg   [4:0] neuron_v_membrane_reg_259_pp0_iter5_reg;
reg   [4:0] neuron_v_membrane_reg_259_pp0_iter6_reg;
reg   [4:0] neuron_v_membrane_reg_259_pp0_iter7_reg;
reg   [4:0] neuron_v_membrane_reg_259_pp0_iter8_reg;
reg   [4:0] neuron_v_membrane_reg_259_pp0_iter9_reg;
reg   [4:0] neuron_v_membrane_reg_259_pp0_iter10_reg;
reg   [4:0] neuron_v_membrane_reg_259_pp0_iter11_reg;
reg   [4:0] neuron_v_membrane_reg_259_pp0_iter12_reg;
reg   [31:0] input_reg_270;
reg   [31:0] mul_i2_reg_275;
reg   [31:0] lif2_neurons_voltage_trace_reg_285;
reg   [31:0] lif2_neurons_voltage_trace_reg_285_pp0_iter12_reg;
wire   [0:0] icmp_ln227_2_fu_161_p2;
reg   [0:0] icmp_ln227_2_reg_297;
wire   [0:0] icmp_ln227_3_fu_167_p2;
reg   [0:0] icmp_ln227_3_reg_302;
wire    ap_block_pp0_stage0;
reg   [5:0] i_fu_46;
wire   [5:0] add_ln308_fu_127_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_i_1;
reg    hidden2_ce0_local;
reg    lif2_neurons_v_membrane_ce1_local;
reg    lif2_neurons_v_membrane_we0_local;
wire   [31:0] select_ln227_fu_224_p3;
reg    lif2_neurons_v_membrane_ce0_local;
reg    lif2_neurons_v_threshold_ce0_local;
wire   [31:0] bitcast_ln227_1_fu_143_p1;
wire   [7:0] tmp_9_fu_147_p4;
wire   [22:0] trunc_ln227_1_fu_157_p1;
wire   [31:0] bitcast_ln227_fu_173_p1;
wire   [7:0] tmp_8_fu_176_p4;
wire   [22:0] trunc_ln227_fu_186_p1;
wire   [0:0] icmp_ln227_1_fu_196_p2;
wire   [0:0] icmp_ln227_fu_190_p2;
wire   [0:0] or_ln227_fu_202_p2;
wire   [0:0] or_ln227_1_fu_208_p2;
wire   [0:0] and_ln227_fu_212_p2;
wire   [0:0] and_ln227_1_fu_218_p2;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 i_fu_46 = 6'd0;
#0 ap_done_reg = 1'b0;
end

snn_infer_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter12_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln308_fu_121_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_46 <= add_ln308_fu_127_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_46 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln227_2_reg_297 <= icmp_ln227_2_fu_161_p2;
        icmp_ln227_3_reg_302 <= icmp_ln227_3_fu_167_p2;
        input_reg_270 <= grp_fu_827_p_dout0;
        lif2_neurons_voltage_trace_reg_285 <= grp_fu_306_p_dout0;
        lif2_neurons_voltage_trace_reg_285_pp0_iter12_reg <= lif2_neurons_voltage_trace_reg_285;
        mul_i2_reg_275 <= grp_fu_313_p_dout0;
        neuron_v_membrane_reg_259 <= zext_ln308_reg_243_pp0_iter1_reg;
        neuron_v_membrane_reg_259_pp0_iter10_reg <= neuron_v_membrane_reg_259_pp0_iter9_reg;
        neuron_v_membrane_reg_259_pp0_iter11_reg <= neuron_v_membrane_reg_259_pp0_iter10_reg;
        neuron_v_membrane_reg_259_pp0_iter12_reg <= neuron_v_membrane_reg_259_pp0_iter11_reg;
        neuron_v_membrane_reg_259_pp0_iter3_reg <= neuron_v_membrane_reg_259;
        neuron_v_membrane_reg_259_pp0_iter4_reg <= neuron_v_membrane_reg_259_pp0_iter3_reg;
        neuron_v_membrane_reg_259_pp0_iter5_reg <= neuron_v_membrane_reg_259_pp0_iter4_reg;
        neuron_v_membrane_reg_259_pp0_iter6_reg <= neuron_v_membrane_reg_259_pp0_iter5_reg;
        neuron_v_membrane_reg_259_pp0_iter7_reg <= neuron_v_membrane_reg_259_pp0_iter6_reg;
        neuron_v_membrane_reg_259_pp0_iter8_reg <= neuron_v_membrane_reg_259_pp0_iter7_reg;
        neuron_v_membrane_reg_259_pp0_iter9_reg <= neuron_v_membrane_reg_259_pp0_iter8_reg;
        zext_ln308_reg_243_pp0_iter10_reg[5 : 0] <= zext_ln308_reg_243_pp0_iter9_reg[5 : 0];
        zext_ln308_reg_243_pp0_iter2_reg[5 : 0] <= zext_ln308_reg_243_pp0_iter1_reg[5 : 0];
        zext_ln308_reg_243_pp0_iter3_reg[5 : 0] <= zext_ln308_reg_243_pp0_iter2_reg[5 : 0];
        zext_ln308_reg_243_pp0_iter4_reg[5 : 0] <= zext_ln308_reg_243_pp0_iter3_reg[5 : 0];
        zext_ln308_reg_243_pp0_iter5_reg[5 : 0] <= zext_ln308_reg_243_pp0_iter4_reg[5 : 0];
        zext_ln308_reg_243_pp0_iter6_reg[5 : 0] <= zext_ln308_reg_243_pp0_iter5_reg[5 : 0];
        zext_ln308_reg_243_pp0_iter7_reg[5 : 0] <= zext_ln308_reg_243_pp0_iter6_reg[5 : 0];
        zext_ln308_reg_243_pp0_iter8_reg[5 : 0] <= zext_ln308_reg_243_pp0_iter7_reg[5 : 0];
        zext_ln308_reg_243_pp0_iter9_reg[5 : 0] <= zext_ln308_reg_243_pp0_iter8_reg[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        hidden2_load_reg_254 <= hidden2_q0;
        zext_ln308_reg_243[5 : 0] <= zext_ln308_fu_133_p1[5 : 0];
        zext_ln308_reg_243_pp0_iter1_reg[5 : 0] <= zext_ln308_reg_243[5 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln308_fu_121_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter12_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 6'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_46;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hidden2_ce0_local = 1'b1;
    end else begin
        hidden2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        lif2_neurons_v_membrane_ce0_local = 1'b1;
    end else begin
        lif2_neurons_v_membrane_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        lif2_neurons_v_membrane_ce1_local = 1'b1;
    end else begin
        lif2_neurons_v_membrane_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        lif2_neurons_v_membrane_we0_local = 1'b1;
    end else begin
        lif2_neurons_v_membrane_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        lif2_neurons_v_threshold_ce0_local = 1'b1;
    end else begin
        lif2_neurons_v_threshold_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln308_fu_127_p2 = (ap_sig_allocacmp_i_1 + 6'd1);

assign and_ln227_1_fu_218_p2 = (grp_fu_327_p_dout0 & and_ln227_fu_212_p2);

assign and_ln227_fu_212_p2 = (or_ln227_fu_202_p2 & or_ln227_1_fu_208_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bitcast_ln227_1_fu_143_p1 = lif2_neurons_v_threshold_q0;

assign bitcast_ln227_fu_173_p1 = lif2_neurons_voltage_trace_reg_285_pp0_iter12_reg;

assign grp_fu_306_p_ce = 1'b1;

assign grp_fu_306_p_din0 = mul_i2_reg_275;

assign grp_fu_306_p_din1 = input_reg_270;

assign grp_fu_306_p_opcode = 2'd0;

assign grp_fu_313_p_ce = 1'b1;

assign grp_fu_313_p_din0 = lif2_neurons_v_membrane_q1;

assign grp_fu_313_p_din1 = 32'd1064534488;

assign grp_fu_327_p_ce = 1'b1;

assign grp_fu_327_p_din0 = lif2_neurons_voltage_trace_reg_285;

assign grp_fu_327_p_din1 = lif2_neurons_v_threshold_q0;

assign grp_fu_327_p_opcode = 5'd3;

assign grp_fu_827_p_ce = 1'b1;

assign grp_fu_827_p_din0 = hidden2_load_reg_254;

assign grp_fu_827_p_din1 = 32'd0;

assign grp_fu_827_p_opcode = 2'd0;

assign hidden2_address0 = zext_ln308_fu_133_p1;

assign hidden2_ce0 = hidden2_ce0_local;

assign icmp_ln227_1_fu_196_p2 = ((trunc_ln227_fu_186_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln227_2_fu_161_p2 = ((tmp_9_fu_147_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln227_3_fu_167_p2 = ((trunc_ln227_1_fu_157_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln227_fu_190_p2 = ((tmp_8_fu_176_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln308_fu_121_p2 = ((ap_sig_allocacmp_i_1 == 6'd32) ? 1'b1 : 1'b0);

assign lif2_neurons_v_membrane_address0 = neuron_v_membrane_reg_259_pp0_iter12_reg;

assign lif2_neurons_v_membrane_address1 = zext_ln308_reg_243_pp0_iter1_reg;

assign lif2_neurons_v_membrane_ce0 = lif2_neurons_v_membrane_ce0_local;

assign lif2_neurons_v_membrane_ce1 = lif2_neurons_v_membrane_ce1_local;

assign lif2_neurons_v_membrane_d0 = select_ln227_fu_224_p3;

assign lif2_neurons_v_membrane_we0 = lif2_neurons_v_membrane_we0_local;

assign lif2_neurons_v_threshold_address0 = zext_ln308_reg_243_pp0_iter10_reg;

assign lif2_neurons_v_threshold_ce0 = lif2_neurons_v_threshold_ce0_local;

assign or_ln227_1_fu_208_p2 = (icmp_ln227_3_reg_302 | icmp_ln227_2_reg_297);

assign or_ln227_fu_202_p2 = (icmp_ln227_fu_190_p2 | icmp_ln227_1_fu_196_p2);

assign select_ln227_fu_224_p3 = ((and_ln227_1_fu_218_p2[0:0] == 1'b1) ? 32'd0 : lif2_neurons_voltage_trace_reg_285_pp0_iter12_reg);

assign tmp_8_fu_176_p4 = {{bitcast_ln227_fu_173_p1[30:23]}};

assign tmp_9_fu_147_p4 = {{bitcast_ln227_1_fu_143_p1[30:23]}};

assign trunc_ln227_1_fu_157_p1 = bitcast_ln227_1_fu_143_p1[22:0];

assign trunc_ln227_fu_186_p1 = bitcast_ln227_fu_173_p1[22:0];

assign zext_ln308_fu_133_p1 = ap_sig_allocacmp_i_1;

always @ (posedge ap_clk) begin
    zext_ln308_reg_243[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln308_reg_243_pp0_iter1_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln308_reg_243_pp0_iter2_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln308_reg_243_pp0_iter3_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln308_reg_243_pp0_iter4_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln308_reg_243_pp0_iter5_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln308_reg_243_pp0_iter6_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln308_reg_243_pp0_iter7_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln308_reg_243_pp0_iter8_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln308_reg_243_pp0_iter9_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln308_reg_243_pp0_iter10_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //snn_infer_snn_infer_Pipeline_VITIS_LOOP_308_6
