// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snn_infer_matrix_multiply (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        input_r_address1,
        input_r_ce1,
        input_r_q1,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0,
        grp_fu_827_p_din0,
        grp_fu_827_p_din1,
        grp_fu_827_p_opcode,
        grp_fu_827_p_dout0,
        grp_fu_827_p_ce,
        grp_fu_306_p_din0,
        grp_fu_306_p_din1,
        grp_fu_306_p_opcode,
        grp_fu_306_p_dout0,
        grp_fu_306_p_ce,
        grp_fu_831_p_din0,
        grp_fu_831_p_din1,
        grp_fu_831_p_opcode,
        grp_fu_831_p_dout0,
        grp_fu_831_p_ce,
        grp_fu_313_p_din0,
        grp_fu_313_p_din1,
        grp_fu_313_p_dout0,
        grp_fu_313_p_ce,
        grp_fu_835_p_din0,
        grp_fu_835_p_din1,
        grp_fu_835_p_dout0,
        grp_fu_835_p_ce,
        grp_fu_839_p_din0,
        grp_fu_839_p_din1,
        grp_fu_839_p_dout0,
        grp_fu_839_p_ce
);

parameter    ap_ST_fsm_state1 = 34'd1;
parameter    ap_ST_fsm_state2 = 34'd2;
parameter    ap_ST_fsm_state3 = 34'd4;
parameter    ap_ST_fsm_state4 = 34'd8;
parameter    ap_ST_fsm_state5 = 34'd16;
parameter    ap_ST_fsm_state6 = 34'd32;
parameter    ap_ST_fsm_state7 = 34'd64;
parameter    ap_ST_fsm_state8 = 34'd128;
parameter    ap_ST_fsm_state9 = 34'd256;
parameter    ap_ST_fsm_state10 = 34'd512;
parameter    ap_ST_fsm_state11 = 34'd1024;
parameter    ap_ST_fsm_state12 = 34'd2048;
parameter    ap_ST_fsm_state13 = 34'd4096;
parameter    ap_ST_fsm_state14 = 34'd8192;
parameter    ap_ST_fsm_state15 = 34'd16384;
parameter    ap_ST_fsm_state16 = 34'd32768;
parameter    ap_ST_fsm_state17 = 34'd65536;
parameter    ap_ST_fsm_state18 = 34'd131072;
parameter    ap_ST_fsm_state19 = 34'd262144;
parameter    ap_ST_fsm_state20 = 34'd524288;
parameter    ap_ST_fsm_state21 = 34'd1048576;
parameter    ap_ST_fsm_state22 = 34'd2097152;
parameter    ap_ST_fsm_state23 = 34'd4194304;
parameter    ap_ST_fsm_state24 = 34'd8388608;
parameter    ap_ST_fsm_state25 = 34'd16777216;
parameter    ap_ST_fsm_state26 = 34'd33554432;
parameter    ap_ST_fsm_state27 = 34'd67108864;
parameter    ap_ST_fsm_state28 = 34'd134217728;
parameter    ap_ST_fsm_state29 = 34'd268435456;
parameter    ap_ST_fsm_state30 = 34'd536870912;
parameter    ap_ST_fsm_state31 = 34'd1073741824;
parameter    ap_ST_fsm_state32 = 34'd2147483648;
parameter    ap_ST_fsm_state33 = 34'd4294967296;
parameter    ap_ST_fsm_state34 = 34'd8589934592;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] input_r_address0;
output   input_r_ce0;
input  [31:0] input_r_q0;
output  [5:0] input_r_address1;
output   input_r_ce1;
input  [31:0] input_r_q1;
output  [4:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [31:0] output_r_d0;
output  [31:0] grp_fu_827_p_din0;
output  [31:0] grp_fu_827_p_din1;
output  [1:0] grp_fu_827_p_opcode;
input  [31:0] grp_fu_827_p_dout0;
output   grp_fu_827_p_ce;
output  [31:0] grp_fu_306_p_din0;
output  [31:0] grp_fu_306_p_din1;
output  [0:0] grp_fu_306_p_opcode;
input  [31:0] grp_fu_306_p_dout0;
output   grp_fu_306_p_ce;
output  [31:0] grp_fu_831_p_din0;
output  [31:0] grp_fu_831_p_din1;
output  [1:0] grp_fu_831_p_opcode;
input  [31:0] grp_fu_831_p_dout0;
output   grp_fu_831_p_ce;
output  [31:0] grp_fu_313_p_din0;
output  [31:0] grp_fu_313_p_din1;
input  [31:0] grp_fu_313_p_dout0;
output   grp_fu_313_p_ce;
output  [31:0] grp_fu_835_p_din0;
output  [31:0] grp_fu_835_p_din1;
input  [31:0] grp_fu_835_p_dout0;
output   grp_fu_835_p_ce;
output  [31:0] grp_fu_839_p_din0;
output  [31:0] grp_fu_839_p_din1;
input  [31:0] grp_fu_839_p_dout0;
output   grp_fu_839_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [33:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] input_load_reg_805;
wire    ap_CS_fsm_state2;
reg   [31:0] input_load_1_reg_810;
reg   [31:0] input_load_2_reg_825;
wire    ap_CS_fsm_state3;
reg   [31:0] input_load_3_reg_830;
reg   [31:0] input_load_4_reg_845;
wire    ap_CS_fsm_state4;
reg   [31:0] input_load_5_reg_850;
reg   [31:0] input_load_6_reg_865;
wire    ap_CS_fsm_state5;
reg   [31:0] input_load_7_reg_870;
reg   [31:0] input_load_8_reg_885;
wire    ap_CS_fsm_state6;
reg   [31:0] input_load_9_reg_890;
reg   [31:0] input_load_10_reg_905;
wire    ap_CS_fsm_state7;
reg   [31:0] input_load_11_reg_910;
reg   [31:0] input_load_12_reg_925;
wire    ap_CS_fsm_state8;
reg   [31:0] input_load_13_reg_930;
reg   [31:0] input_load_14_reg_945;
wire    ap_CS_fsm_state9;
reg   [31:0] input_load_15_reg_950;
reg   [31:0] input_load_16_reg_965;
wire    ap_CS_fsm_state10;
reg   [31:0] input_load_17_reg_970;
reg   [31:0] input_load_18_reg_985;
wire    ap_CS_fsm_state11;
reg   [31:0] input_load_19_reg_990;
reg   [31:0] input_load_20_reg_1005;
wire    ap_CS_fsm_state12;
reg   [31:0] input_load_21_reg_1010;
reg   [31:0] input_load_22_reg_1025;
wire    ap_CS_fsm_state13;
reg   [31:0] input_load_23_reg_1030;
reg   [31:0] input_load_24_reg_1045;
wire    ap_CS_fsm_state14;
reg   [31:0] input_load_25_reg_1050;
reg   [31:0] input_load_26_reg_1065;
wire    ap_CS_fsm_state15;
reg   [31:0] input_load_27_reg_1070;
reg   [31:0] input_load_28_reg_1085;
wire    ap_CS_fsm_state16;
reg   [31:0] input_load_29_reg_1090;
reg   [31:0] input_load_30_reg_1105;
wire    ap_CS_fsm_state17;
reg   [31:0] input_load_31_reg_1110;
reg   [31:0] input_load_32_reg_1125;
wire    ap_CS_fsm_state18;
reg   [31:0] input_load_33_reg_1130;
reg   [31:0] input_load_34_reg_1145;
wire    ap_CS_fsm_state19;
reg   [31:0] input_load_35_reg_1150;
reg   [31:0] input_load_36_reg_1165;
wire    ap_CS_fsm_state20;
reg   [31:0] input_load_37_reg_1170;
reg   [31:0] input_load_38_reg_1185;
wire    ap_CS_fsm_state21;
reg   [31:0] input_load_39_reg_1190;
reg   [31:0] input_load_40_reg_1205;
wire    ap_CS_fsm_state22;
reg   [31:0] input_load_41_reg_1210;
reg   [31:0] input_load_42_reg_1225;
wire    ap_CS_fsm_state23;
reg   [31:0] input_load_43_reg_1230;
reg   [31:0] input_load_44_reg_1245;
wire    ap_CS_fsm_state24;
reg   [31:0] input_load_45_reg_1250;
reg   [31:0] input_load_46_reg_1265;
wire    ap_CS_fsm_state25;
reg   [31:0] input_load_47_reg_1270;
reg   [31:0] input_load_48_reg_1285;
wire    ap_CS_fsm_state26;
reg   [31:0] input_load_49_reg_1290;
reg   [31:0] input_load_50_reg_1305;
wire    ap_CS_fsm_state27;
reg   [31:0] input_load_51_reg_1310;
reg   [31:0] input_load_52_reg_1325;
wire    ap_CS_fsm_state28;
reg   [31:0] input_load_53_reg_1330;
reg   [31:0] input_load_54_reg_1345;
wire    ap_CS_fsm_state29;
reg   [31:0] input_load_55_reg_1350;
reg   [31:0] input_load_56_reg_1365;
wire    ap_CS_fsm_state30;
reg   [31:0] input_load_57_reg_1370;
reg   [31:0] input_load_58_reg_1385;
wire    ap_CS_fsm_state31;
reg   [31:0] input_load_59_reg_1390;
reg   [31:0] input_load_60_reg_1405;
wire    ap_CS_fsm_state32;
reg   [31:0] input_load_61_reg_1410;
reg   [31:0] input_load_62_reg_1425;
wire    ap_CS_fsm_state33;
reg   [31:0] input_load_63_reg_1430;
wire    grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_ap_start;
wire    grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_ap_done;
wire    grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_ap_idle;
wire    grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_ap_ready;
wire   [4:0] grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_output_r_address0;
wire    grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_output_r_ce0;
wire    grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_output_r_we0;
wire   [31:0] grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_output_r_d0;
wire   [31:0] grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1435_p_din0;
wire   [31:0] grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1435_p_din1;
wire   [1:0] grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1435_p_opcode;
wire    grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1435_p_ce;
wire   [31:0] grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1439_p_din0;
wire   [31:0] grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1439_p_din1;
wire   [0:0] grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1439_p_opcode;
wire    grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1439_p_ce;
wire   [31:0] grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1443_p_din0;
wire   [31:0] grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1443_p_din1;
wire   [1:0] grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1443_p_opcode;
wire    grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1443_p_ce;
wire   [31:0] grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1447_p_din0;
wire   [31:0] grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1447_p_din1;
wire    grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1447_p_ce;
wire   [31:0] grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1451_p_din0;
wire   [31:0] grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1451_p_din1;
wire    grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1451_p_ce;
wire   [31:0] grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1455_p_din0;
wire   [31:0] grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1455_p_din1;
wire    grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1455_p_ce;
reg    grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_ap_start_reg;
wire    ap_CS_fsm_state34;
reg    input_r_ce1_local;
reg   [5:0] input_r_address1_local;
reg    input_r_ce0_local;
reg   [5:0] input_r_address0_local;
reg    grp_fu_1435_ce;
reg    grp_fu_1439_ce;
reg    grp_fu_1443_ce;
reg    grp_fu_1447_ce;
reg    grp_fu_1451_ce;
reg    grp_fu_1455_ce;
reg   [33:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
reg    ap_ST_fsm_state34_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 34'd1;
#0 grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_ap_start_reg = 1'b0;
end

snn_infer_matrix_multiply_Pipeline_VITIS_LOOP_244_1 grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_ap_start),
    .ap_done(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_ap_done),
    .ap_idle(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_ap_idle),
    .ap_ready(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_ap_ready),
    .input_load(input_load_reg_805),
    .input_load_1(input_load_1_reg_810),
    .input_load_2(input_load_2_reg_825),
    .input_load_3(input_load_3_reg_830),
    .input_load_4(input_load_4_reg_845),
    .input_load_5(input_load_5_reg_850),
    .input_load_6(input_load_6_reg_865),
    .input_load_7(input_load_7_reg_870),
    .input_load_8(input_load_8_reg_885),
    .input_load_9(input_load_9_reg_890),
    .input_load_10(input_load_10_reg_905),
    .input_load_11(input_load_11_reg_910),
    .input_load_12(input_load_12_reg_925),
    .input_load_13(input_load_13_reg_930),
    .input_load_14(input_load_14_reg_945),
    .input_load_15(input_load_15_reg_950),
    .input_load_16(input_load_16_reg_965),
    .input_load_17(input_load_17_reg_970),
    .input_load_18(input_load_18_reg_985),
    .input_load_19(input_load_19_reg_990),
    .input_load_20(input_load_20_reg_1005),
    .input_load_21(input_load_21_reg_1010),
    .input_load_22(input_load_22_reg_1025),
    .input_load_23(input_load_23_reg_1030),
    .input_load_24(input_load_24_reg_1045),
    .input_load_25(input_load_25_reg_1050),
    .input_load_26(input_load_26_reg_1065),
    .input_load_27(input_load_27_reg_1070),
    .input_load_28(input_load_28_reg_1085),
    .input_load_29(input_load_29_reg_1090),
    .input_load_30(input_load_30_reg_1105),
    .input_load_31(input_load_31_reg_1110),
    .input_load_32(input_load_32_reg_1125),
    .input_load_33(input_load_33_reg_1130),
    .input_load_34(input_load_34_reg_1145),
    .input_load_35(input_load_35_reg_1150),
    .input_load_36(input_load_36_reg_1165),
    .input_load_37(input_load_37_reg_1170),
    .input_load_38(input_load_38_reg_1185),
    .input_load_39(input_load_39_reg_1190),
    .input_load_40(input_load_40_reg_1205),
    .input_load_41(input_load_41_reg_1210),
    .input_load_42(input_load_42_reg_1225),
    .input_load_43(input_load_43_reg_1230),
    .input_load_44(input_load_44_reg_1245),
    .input_load_45(input_load_45_reg_1250),
    .input_load_46(input_load_46_reg_1265),
    .input_load_47(input_load_47_reg_1270),
    .input_load_48(input_load_48_reg_1285),
    .input_load_49(input_load_49_reg_1290),
    .input_load_50(input_load_50_reg_1305),
    .input_load_51(input_load_51_reg_1310),
    .input_load_52(input_load_52_reg_1325),
    .input_load_53(input_load_53_reg_1330),
    .input_load_54(input_load_54_reg_1345),
    .input_load_55(input_load_55_reg_1350),
    .input_load_56(input_load_56_reg_1365),
    .input_load_57(input_load_57_reg_1370),
    .input_load_58(input_load_58_reg_1385),
    .input_load_59(input_load_59_reg_1390),
    .input_load_60(input_load_60_reg_1405),
    .input_load_61(input_load_61_reg_1410),
    .input_load_62(input_load_62_reg_1425),
    .input_load_63(input_load_63_reg_1430),
    .output_r_address0(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_output_r_address0),
    .output_r_ce0(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_output_r_ce0),
    .output_r_we0(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_output_r_we0),
    .output_r_d0(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_output_r_d0),
    .grp_fu_1435_p_din0(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1435_p_din0),
    .grp_fu_1435_p_din1(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1435_p_din1),
    .grp_fu_1435_p_opcode(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1435_p_opcode),
    .grp_fu_1435_p_dout0(grp_fu_827_p_dout0),
    .grp_fu_1435_p_ce(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1435_p_ce),
    .grp_fu_1439_p_din0(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1439_p_din0),
    .grp_fu_1439_p_din1(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1439_p_din1),
    .grp_fu_1439_p_opcode(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1439_p_opcode),
    .grp_fu_1439_p_dout0(grp_fu_306_p_dout0),
    .grp_fu_1439_p_ce(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1439_p_ce),
    .grp_fu_1443_p_din0(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1443_p_din0),
    .grp_fu_1443_p_din1(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1443_p_din1),
    .grp_fu_1443_p_opcode(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1443_p_opcode),
    .grp_fu_1443_p_dout0(grp_fu_831_p_dout0),
    .grp_fu_1443_p_ce(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1443_p_ce),
    .grp_fu_1447_p_din0(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1447_p_din0),
    .grp_fu_1447_p_din1(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1447_p_din1),
    .grp_fu_1447_p_dout0(grp_fu_313_p_dout0),
    .grp_fu_1447_p_ce(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1447_p_ce),
    .grp_fu_1451_p_din0(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1451_p_din0),
    .grp_fu_1451_p_din1(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1451_p_din1),
    .grp_fu_1451_p_dout0(grp_fu_835_p_dout0),
    .grp_fu_1451_p_ce(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1451_p_ce),
    .grp_fu_1455_p_din0(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1455_p_din0),
    .grp_fu_1455_p_din1(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1455_p_din1),
    .grp_fu_1455_p_dout0(grp_fu_839_p_dout0),
    .grp_fu_1455_p_ce(grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1455_p_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state33)) begin
            grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_ap_start_reg <= 1'b1;
        end else if ((grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_ap_ready == 1'b1)) begin
            grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        input_load_10_reg_905 <= input_r_q1;
        input_load_11_reg_910 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        input_load_12_reg_925 <= input_r_q1;
        input_load_13_reg_930 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        input_load_14_reg_945 <= input_r_q1;
        input_load_15_reg_950 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        input_load_16_reg_965 <= input_r_q1;
        input_load_17_reg_970 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        input_load_18_reg_985 <= input_r_q1;
        input_load_19_reg_990 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        input_load_1_reg_810 <= input_r_q0;
        input_load_reg_805 <= input_r_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        input_load_20_reg_1005 <= input_r_q1;
        input_load_21_reg_1010 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        input_load_22_reg_1025 <= input_r_q1;
        input_load_23_reg_1030 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        input_load_24_reg_1045 <= input_r_q1;
        input_load_25_reg_1050 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        input_load_26_reg_1065 <= input_r_q1;
        input_load_27_reg_1070 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        input_load_28_reg_1085 <= input_r_q1;
        input_load_29_reg_1090 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_load_2_reg_825 <= input_r_q1;
        input_load_3_reg_830 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        input_load_30_reg_1105 <= input_r_q1;
        input_load_31_reg_1110 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        input_load_32_reg_1125 <= input_r_q1;
        input_load_33_reg_1130 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        input_load_34_reg_1145 <= input_r_q1;
        input_load_35_reg_1150 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        input_load_36_reg_1165 <= input_r_q1;
        input_load_37_reg_1170 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        input_load_38_reg_1185 <= input_r_q1;
        input_load_39_reg_1190 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        input_load_40_reg_1205 <= input_r_q1;
        input_load_41_reg_1210 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        input_load_42_reg_1225 <= input_r_q1;
        input_load_43_reg_1230 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        input_load_44_reg_1245 <= input_r_q1;
        input_load_45_reg_1250 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        input_load_46_reg_1265 <= input_r_q1;
        input_load_47_reg_1270 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        input_load_48_reg_1285 <= input_r_q1;
        input_load_49_reg_1290 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_load_4_reg_845 <= input_r_q1;
        input_load_5_reg_850 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        input_load_50_reg_1305 <= input_r_q1;
        input_load_51_reg_1310 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        input_load_52_reg_1325 <= input_r_q1;
        input_load_53_reg_1330 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        input_load_54_reg_1345 <= input_r_q1;
        input_load_55_reg_1350 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        input_load_56_reg_1365 <= input_r_q1;
        input_load_57_reg_1370 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        input_load_58_reg_1385 <= input_r_q1;
        input_load_59_reg_1390 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        input_load_60_reg_1405 <= input_r_q1;
        input_load_61_reg_1410 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        input_load_62_reg_1425 <= input_r_q1;
        input_load_63_reg_1430 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_load_6_reg_865 <= input_r_q1;
        input_load_7_reg_870 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        input_load_8_reg_885 <= input_r_q1;
        input_load_9_reg_890 <= input_r_q0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

always @ (*) begin
    if ((grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_ap_done == 1'b0)) begin
        ap_ST_fsm_state34_blk = 1'b1;
    end else begin
        ap_ST_fsm_state34_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state34)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state34))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        grp_fu_1435_ce = grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1435_p_ce;
    end else begin
        grp_fu_1435_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        grp_fu_1439_ce = grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1439_p_ce;
    end else begin
        grp_fu_1439_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        grp_fu_1443_ce = grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1443_p_ce;
    end else begin
        grp_fu_1443_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        grp_fu_1447_ce = grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1447_p_ce;
    end else begin
        grp_fu_1447_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        grp_fu_1451_ce = grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1451_p_ce;
    end else begin
        grp_fu_1451_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        grp_fu_1455_ce = grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1455_p_ce;
    end else begin
        grp_fu_1455_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        input_r_address0_local = 64'd63;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        input_r_address0_local = 64'd61;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        input_r_address0_local = 64'd59;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        input_r_address0_local = 64'd57;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        input_r_address0_local = 64'd55;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        input_r_address0_local = 64'd53;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        input_r_address0_local = 64'd51;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        input_r_address0_local = 64'd49;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        input_r_address0_local = 64'd47;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        input_r_address0_local = 64'd45;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        input_r_address0_local = 64'd43;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        input_r_address0_local = 64'd41;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        input_r_address0_local = 64'd39;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        input_r_address0_local = 64'd37;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        input_r_address0_local = 64'd35;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        input_r_address0_local = 64'd33;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        input_r_address0_local = 64'd31;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        input_r_address0_local = 64'd29;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        input_r_address0_local = 64'd27;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        input_r_address0_local = 64'd25;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        input_r_address0_local = 64'd23;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        input_r_address0_local = 64'd21;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        input_r_address0_local = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        input_r_address0_local = 64'd17;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        input_r_address0_local = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        input_r_address0_local = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        input_r_address0_local = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        input_r_address0_local = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        input_r_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_r_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_r_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        input_r_address0_local = 64'd1;
    end else begin
        input_r_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        input_r_address1_local = 64'd62;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        input_r_address1_local = 64'd60;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        input_r_address1_local = 64'd58;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        input_r_address1_local = 64'd56;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        input_r_address1_local = 64'd54;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        input_r_address1_local = 64'd52;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        input_r_address1_local = 64'd50;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        input_r_address1_local = 64'd48;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        input_r_address1_local = 64'd46;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        input_r_address1_local = 64'd44;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        input_r_address1_local = 64'd42;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        input_r_address1_local = 64'd40;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        input_r_address1_local = 64'd38;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        input_r_address1_local = 64'd36;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        input_r_address1_local = 64'd34;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        input_r_address1_local = 64'd32;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        input_r_address1_local = 64'd30;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        input_r_address1_local = 64'd28;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        input_r_address1_local = 64'd26;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        input_r_address1_local = 64'd24;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        input_r_address1_local = 64'd22;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        input_r_address1_local = 64'd20;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        input_r_address1_local = 64'd18;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        input_r_address1_local = 64'd16;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        input_r_address1_local = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        input_r_address1_local = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        input_r_address1_local = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        input_r_address1_local = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        input_r_address1_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_r_address1_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_r_address1_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        input_r_address1_local = 64'd0;
    end else begin
        input_r_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        input_r_ce0_local = 1'b1;
    end else begin
        input_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        input_r_ce1_local = 1'b1;
    end else begin
        input_r_ce1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            if (((grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state34))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign grp_fu_306_p_ce = grp_fu_1439_ce;

assign grp_fu_306_p_din0 = grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1439_p_din0;

assign grp_fu_306_p_din1 = grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1439_p_din1;

assign grp_fu_306_p_opcode = grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1439_p_opcode;

assign grp_fu_313_p_ce = grp_fu_1447_ce;

assign grp_fu_313_p_din0 = grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1447_p_din0;

assign grp_fu_313_p_din1 = grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1447_p_din1;

assign grp_fu_827_p_ce = grp_fu_1435_ce;

assign grp_fu_827_p_din0 = grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1435_p_din0;

assign grp_fu_827_p_din1 = grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1435_p_din1;

assign grp_fu_827_p_opcode = 2'd0;

assign grp_fu_831_p_ce = grp_fu_1443_ce;

assign grp_fu_831_p_din0 = grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1443_p_din0;

assign grp_fu_831_p_din1 = grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1443_p_din1;

assign grp_fu_831_p_opcode = 2'd0;

assign grp_fu_835_p_ce = grp_fu_1451_ce;

assign grp_fu_835_p_din0 = grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1451_p_din0;

assign grp_fu_835_p_din1 = grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1451_p_din1;

assign grp_fu_839_p_ce = grp_fu_1455_ce;

assign grp_fu_839_p_din0 = grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1455_p_din0;

assign grp_fu_839_p_din1 = grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_grp_fu_1455_p_din1;

assign grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_ap_start = grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_ap_start_reg;

assign input_r_address0 = input_r_address0_local;

assign input_r_address1 = input_r_address1_local;

assign input_r_ce0 = input_r_ce0_local;

assign input_r_ce1 = input_r_ce1_local;

assign output_r_address0 = grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_output_r_address0;

assign output_r_ce0 = grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_output_r_ce0;

assign output_r_d0 = grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_output_r_d0;

assign output_r_we0 = grp_matrix_multiply_Pipeline_VITIS_LOOP_244_1_fu_721_output_r_we0;

endmodule //snn_infer_matrix_multiply
